<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currencies = [

            'AFN' => [
                'name' => 'Afghani',
                'abbr' => 'AFN',
                'code' => '971',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '؋',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'subunit_name' => 'Pul',
                'locale' => 'fa_AF',
            ],

            'EUR' => [
                'name' => 'Euro',
                'abbr' => 'EUR',
                'code' => '978',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '€',
                'symbol_first' => true,
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'subunit_name' => 'Cent',
                'locale' => 'en_US',

            ],

            'ALL' => [
                'name' => 'Lek',
                'abbr' => 'ALL',
                'code' => '008',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'L',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'subunit_name' => 'Qindarka',
                'locale' => 'sq_AL',
            ],

            'DZD' => [
                'name' => 'Algerian Dinar',
                'abbr' => 'DZD',
                'code' => '012',
                'subunit_name' => 'Centime',
                'locale' => 'ar_DZ',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'د.ج',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'USD' => [
                'name' => 'US Dollar',
                'abbr' => 'USD',
                'code' => '840',
                'subunit_name' => 'Cent',
                'locale' => 'en_US',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'AOA' => [
                'name' => 'Kwanza',
                'abbr' => 'AOA',
                'code' => '973',
                'subunit_name' => 'Cêntimo',
                'locale' => 'pt_AO',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'Kz',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'XCD' => [
                'name' => 'East Caribbean Dollar',
                'abbr' => 'XCD',
                'code' => '951',
                'subunit_name' => 'Cent',
                'locale' => 'en_US',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'ARS' => [
                'name' => 'Argentine Peso',
                'abbr' => 'ARS',
                'code' => '032',
                'subunit_name' => 'Centavo',
                'locale' => 'es_AR',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => true,
                'decimal_mark' => ',',
                'thousands_separator' => '.',
            ],

            'AMD' => [
                'name' => 'Armenian Dram',
                'abbr' => 'AMD',
                'code' => '051',
                'subunit_name' => 'Luma',
                'locale' => 'hy_AM',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '֏',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'AWG' => [
                'name' => 'Aruban Florin',
                'abbr' => 'AWG',
                'code' => '533',
                'subunit_name' => 'Cent',
                'locale' => 'en_US',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'ƒ',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'AUD' => [
                'name' => 'Australian Dollar',
                'abbr' => 'AUD',
                'code' => '036',
                'subunit_name' => 'Cent',
                'locale' => 'en_AU',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'AZN' => [
                'name' => 'Azerbaijan Manat',
                'abbr' => 'AZN',
                'code' => '944',
                'subunit_name' => 'Qəpik',
                'locale' => 'az_AZ',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₼',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'BSD' => [
                'name' => 'Bahamian Dollar',
                'abbr' => 'BSD',
                'code' => '044',
                'subunit_name' => 'Cent',
                'locale' => 'en_BS',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'BHD' => [
                'name' => 'Bahraini Dinar',
                'abbr' => 'BHD',
                'code' => '048',
                'subunit_name' => 'Fils',
                'locale' => 'ar_BH',
                'precision' => 3,
                'subunit' => 1000,
                'symbol' => '.د.ب',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'BDT' => [
                'name' => 'Taka',
                'abbr' => 'BDT',
                'code' => '050',
                'subunit_name' => 'Poisha',
                'locale' => 'bn_BD',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '৳',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'BBD' => [
                'name' => 'Barbados Dollar',
                'abbr' => 'BBD',
                'code' => '052',
                'subunit_name' => 'Cent',
                'locale' => 'en_BB',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'BYN' => [
                'name' => 'Belarusian Ruble',
                'abbr' => 'BYN',
                'code' => '933',
                'subunit_name' => 'Kapyeyka',
                'locale' => 'be_BY',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'Br',
                'symbol_first' => false,
                'decimal_mark' => ',',
                'thousands_separator' => '',
            ],

            'BZD' => [
                'name' => 'Belize Dollar',
                'abbr' => 'BZD',
                'code' => '084',
                'subunit_name' => 'Cent',
                'locale' => 'nl_BE',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'BZ$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'XOF' => [
                'name' => 'CFA Franc BCEAO',
                'abbr' => 'XOF',
                'code' => '952',
                'subunit_name' => 'Centime',
                'locale' => 'fr_BJ',
                'precision' => 0,
                'subunit' => 1,
                'symbol' => 'CFA',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'BMD' => [
                'name' => 'Bermudian Dollar',
                'abbr' => 'BMD',
                'code' => '060',
                'subunit_name' => 'Cent',
                'locale' => 'en_US',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'INR' => [
                'name' => 'Indian Rupee',
                'abbr' => 'INR',
                'code' => '356',
                'subunit_name' => 'Paisa',
                'locale' => 'hi_IN',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₹',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'BTN' => [
                'name' => 'Ngultrum',
                'abbr' => 'BTN',
                'code' => '064',
                'subunit_name' => 'Chetrum',
                'locale' => 'dz_BT',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'Nu.',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'BOB' => [
                'name' => 'Boliviano',
                'abbr' => 'BOB',
                'code' => '068',
                'subunit_name' => 'Centavo',
                'locale' => 'es_BO',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$b',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'BOV' => [
                'name' => 'Mvdol',
                'abbr' => 'BOV',
                'code' => '984',
                'subunit_name' => 'Centavo',
                'locale' => 'es_BO',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'BOV',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'BAM' => [
                'name' => 'Convertible Mark',
                'abbr' => 'BAM',
                'code' => '977',
                'subunit_name' => 'Fening',
                'locale' => 'bs_BA',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'KM',
                'symbol_first' => true,
                'decimal_mark' => ',',
                'thousands_separator' => '.',
            ],

            'BWP' => [
                'name' => 'Pula',
                'abbr' => 'BWP',
                'code' => '072',
                'subunit_name' => 'Thebe',
                'locale' => 'en_BW',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'P',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'NOK' => [
                'name' => 'Norwegian Krone',
                'abbr' => 'NOK',
                'code' => '578',
                'subunit_name' => 'Øre',
                'locale' => 'da_DK',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'kr',
                'symbol_first' => false,
                'decimal_mark' => ',',
                'thousands_separator' => '',
            ],

            'BRL' => [
                'name' => 'Brazilian Real',
                'abbr' => 'BRL',
                'code' => '986',
                'subunit_name' => 'Centavo',
                'locale' => 'pt_BR',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'R$',
                'symbol_first' => true,
                'decimal_mark' => ',',
                'thousands_separator' => '.',
            ],

            'BND' => [
                'name' => 'Brunei Dollar',
                'abbr' => 'BND',
                'code' => '096',
                'subunit_name' => 'Sen',
                'locale' => 'ms_BN',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'BGN' => [
                'name' => 'Bulgarian Lev',
                'abbr' => 'BGN',
                'code' => '975',
                'subunit_name' => 'Stotinka',
                'locale' => 'bg_BG',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'лв',
                'symbol_first' => false,
                'decimal_mark' => ',',
                'thousands_separator' => '',
            ],

            'BIF' => [
                'name' => 'Burundi Franc',
                'abbr' => 'BIF',
                'code' => '108',
                'subunit_name' => 'Centime',
                'locale' => 'fr_BI',
                'precision' => 0,
                'subunit' => 1,
                'symbol' => 'FBu',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'CVE' => [
                'name' => 'Cabo Verde Escudo',
                'abbr' => 'CVE',
                'code' => '132',
                'subunit_name' => 'Centavo',
                'locale' => 'pt_CV',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'KHR' => [
                'name' => 'Riel',
                'abbr' => 'KHR',
                'code' => '116',
                'subunit_name' => 'Sen',
                'locale' => 'km_KH',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '៛',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'XAF' => [
                'name' => 'CFA Franc BEAC',
                'abbr' => 'XAF',
                'code' => '950',
                'subunit_name' => 'Centime',
                'locale' => 'fr_CM',
                'precision' => 0,
                'subunit' => 1,
                'symbol' => 'FCFA',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'CAD' => [
                'name' => 'Canadian Dollar',
                'abbr' => 'CAD',
                'code' => '124',
                'subunit_name' => 'Cent',
                'locale' => 'en_CA',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'KYD' => [
                'name' => 'Cayman Islands Dollar',
                'abbr' => 'KYD',
                'code' => '136',
                'subunit_name' => 'Cent',
                'locale' => 'en_US',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'CLP' => [
                'name' => 'Chilean Peso',
                'abbr' => 'CLP',
                'code' => '152',
                'subunit_name' => 'Centavo',
                'locale' => 'es_CL',
                'precision' => 0,
                'subunit' => 1,
                'symbol' => '$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => '.',
            ],

            'CNY' => [
                'name' => 'Yuan Renminbi',
                'abbr' => 'CNY',
                'code' => '156',
                'subunit_name' => 'Jiao',
                'locale' => 'zh_CN',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '¥',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'COP' => [
                'name' => 'Colombian Peso',
                'abbr' => 'COP',
                'code' => '170',
                'subunit_name' => 'Centavo',
                'locale' => 'es_CO',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => true,
                'decimal_mark' => ',',
                'thousands_separator' => '.',
            ],

            'KMF' => [
                'name' => 'Comorian Franc ',
                'abbr' => 'KMF',
                'code' => '174',
                'subunit_name' => 'Centime',
                'locale' => 'ar_KM',
                'precision' => 0,
                'subunit' => 1,
                'symbol' => 'CF',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'CDF' => [
                'name' => 'Congolese Franc',
                'abbr' => 'CDF',
                'code' => '976',
                'subunit_name' => 'Centime',
                'locale' => 'fr_CG',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'FC',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'NZD' => [
                'name' => 'New Zealand Dollar',
                'abbr' => 'NZD',
                'code' => '554',
                'subunit_name' => 'Cent',
                'locale' => 'en_NZ',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'CRC' => [
                'name' => 'Costa Rican Colon',
                'abbr' => 'CRC',
                'code' => '188',
                'subunit_name' => 'Céntimo',
                'locale' => 'es_CR',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₡',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'CUP' => [
                'name' => 'Cuban Peso',
                'abbr' => 'CUP',
                'code' => '192',
                'subunit_name' => 'Céntimo',
                'locale' => 'es_CU',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₱',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'CUC' => [
                'name' => 'Peso Convertible',
                'abbr' => 'CUC',
                'code' => '931',
                'subunit_name' => 'Céntimo',
                'locale' => 'es_CU',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'ANG' => [
                'name' => 'Netherlands Antillean Guilder',
                'abbr' => 'ANG',
                'code' => '532',
                'subunit_name' => 'Cent',
                'locale' => 'nl_NL',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'ƒ',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'CZK' => [
                'name' => 'Czech Koruna',
                'abbr' => 'CZK',
                'code' => '203',
                'subunit_name' => 'Haléř',
                'locale' => 'cs_CZ',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'Kč',
                'symbol_first' => false,
                'decimal_mark' => ',',
                'thousands_separator' => '.',
            ],

            'DKK' => [
                'name' => 'Danish Krone',
                'abbr' => 'DKK',
                'code' => '208',
                'subunit_name' => 'Øre',
                'locale' => 'da_DK',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'kr',
                'symbol_first' => false,
                'decimal_mark' => ',',
                'thousands_separator' => '.',
            ],

            'DJF' => [
                'name' => 'Djibouti Franc',
                'abbr' => 'DJF',
                'code' => '262',
                'subunit_name' => 'Centime',
                'locale' => 'fr_DJ',
                'precision' => 0,
                'subunit' => 1,
                'symbol' => 'Fdj',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'DOP' => [
                'name' => 'Dominican Peso',
                'abbr' => 'DOP',
                'code' => '214',
                'subunit_name' => 'Centavo',
                'locale' => 'es_DO',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'RD$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'EGP' => [
                'name' => 'Egyptian Pound',
                'abbr' => 'EGP',
                'code' => '818',
                'subunit_name' => 'Piastre',
                'locale' => 'ar_EG',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '£',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'SVC' => [
                'name' => 'El Salvador Colon',
                'abbr' => 'SVC',
                'code' => '222',
                'subunit_name' => 'Peso',
                'locale' => 'es_SV',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'ERN' => [
                'name' => 'Nakfa',
                'abbr' => 'ERN',
                'code' => '232',
                'subunit_name' => 'Cent',
                'locale' => 'ti_ER',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'Nfk',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'SZL' => [
                'name' => 'Lilangeni',
                'abbr' => 'SZL',
                'code' => '748',
                'subunit_name' => 'Cent',
                'locale' => 'en_US',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'E',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'ETB' => [
                'name' => 'Ethiopian Birr',
                'abbr' => 'ETB',
                'code' => '230',
                'subunit_name' => 'Santim',
                'locale' => 'am_ET',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'Br',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'FKP' => [
                'name' => 'Falkland Islands Pound',
                'abbr' => 'FKP',
                'code' => '238',
                'subunit_name' => 'Penny',
                'locale' => 'en_FK',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '£',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'FJD' => [
                'name' => 'Fiji Dollar',
                'abbr' => 'FJD',
                'code' => '242',
                'subunit_name' => 'Cent',
                'locale' => 'en_FJ',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'XPF' => [
                'name' => 'CFP Franc',
                'abbr' => 'XPF',
                'code' => '953',
                'subunit_name' => 'Centime',
                'locale' => 'fr_FR',
                'precision' => 0,
                'subunit' => 1,
                'symbol' => '₣',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'GMD' => [
                'name' => 'Dalasi',
                'abbr' => 'GMD',
                'code' => '270',
                'subunit_name' => 'Butut',
                'locale' => 'en_GM',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'D',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'GEL' => [
                'name' => 'Lari',
                'abbr' => 'GEL',
                'code' => '981',
                'subunit_name' => 'Tetri',
                'locale' => 'ka_GE',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₾',
                'symbol_first' => false,
                'decimal_mark' => ',',
                'thousands_separator' => '.',
            ],

            'GHS' => [
                'name' => 'Ghana Cedi',
                'abbr' => 'GHS',
                'code' => '936',
                'subunit_name' => 'Pesewa',
                'locale' => 'en_GH',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'GH₵',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'GIP' => [
                'name' => 'Gibraltar Pound',
                'abbr' => 'GIP',
                'code' => '292',
                'subunit_name' => 'Penny',
                'locale' => 'en_GI',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '£',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'GTQ' => [
                'name' => 'Quetzal',
                'abbr' => 'GTQ',
                'code' => '320',
                'subunit_name' => 'Centavo',
                'locale' => 'es_GT',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'Q',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'GBP' => [
                'name' => 'Pound Sterling',
                'abbr' => 'GBP',
                'code' => '826',
                'subunit_name' => 'Cent',
                'locale' => 'en_GB',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '£',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'GNF' => [
                'name' => 'Guinean Franc',
                'abbr' => 'GNF',
                'code' => '324',
                'subunit_name' => 'Centime',
                'locale' => 'fr_GN',
                'precision' => 0,
                'subunit' => 1,
                'symbol' => 'FG',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'GYD' => [
                'name' => 'Guyana Dollar',
                'abbr' => 'GYD',
                'code' => '328',
                'subunit_name' => 'Cent',
                'locale' => 'en_GY',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'HTG' => [
                'name' => 'Gourde',
                'abbr' => 'HTG',
                'code' => '332',
                'subunit_name' => 'Centime',
                'locale' => 'fr_HT',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'G',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'HNL' => [
                'name' => 'Lempira',
                'abbr' => 'HNL',
                'code' => '340',
                'subunit_name' => 'Centavo',
                'locale' => 'es_HN',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'L',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'HKD' => [
                'name' => 'Hong Kong Dollar',
                'abbr' => 'HKD',
                'code' => '344',
                'subunit_name' => 'Cent',
                'locale' => 'zh_HK',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'HUF' => [
                'name' => 'Forint',
                'abbr' => 'HUF',
                'code' => '348',
                'subunit_name' => 'Filler',
                'locale' => 'hu_Hu',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'Ft',
                'symbol_first' => false,
                'decimal_mark' => ',',
                'thousands_separator' => '',
            ],

            'ISK' => [
                'name' => 'Iceland Krona',
                'abbr' => 'ISK',
                'code' => '352',
                'subunit_name' => 'Eyrir',
                'locale' => 'is_IS',
                'precision' => 0,
                'subunit' => 1,
                'symbol' => 'kr',
                'symbol_first' => true,
                'decimal_mark' => ',',
                'thousands_separator' => '.',
            ],

            'IDR' => [
                'name' => 'Rupiah',
                'abbr' => 'IDR',
                'code' => '360',
                'subunit_name' => 'Sen',
                'locale' => 'id_ID',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'Rp',
                'symbol_first' => true,
                'decimal_mark' => ',',
                'thousands_separator' => '.',
            ],

            'IRR' => [
                'name' => 'Iranian Rial',
                'abbr' => 'IRR',
                'code' => '364',
                'subunit_name' => 'Dinar',
                'locale' => 'fa_IR',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '﷼',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'IQD' => [
                'name' => 'Iraqi Dinar',
                'abbr' => 'IQD',
                'code' => '368',
                'subunit_name' => 'Fils',
                'locale' => 'ar_IQ',
                'precision' => 3,
                'subunit' => 1000,
                'symbol' => 'ع.د',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'ILS' => [
                'name' => 'New Israeli Sheqel',
                'abbr' => 'ILS',
                'code' => '376',
                'subunit_name' => 'Agorot',
                'locale' => 'he_IL',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₪',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'JMD' => [
                'name' => 'Jamaican Dollar',
                'abbr' => 'JMD',
                'code' => '388',
                'subunit_name' => 'Cent',
                'locale' => 'en_JM',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'J$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'JPY' => [
                'name' => 'Yen',
                'abbr' => 'JPY',
                'code' => '392',
                'subunit_name' => 'Sen',
                'locale' => 'ja_JP',
                'precision' => 0,
                'subunit' => 1,
                'symbol' => '¥',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'JOD' => [
                'name' => 'Jordanian Dinar',
                'abbr' => 'JOD',
                'code' => '400',
                'subunit_name' => 'Piastre',
                'locale' => 'ar_JO',
                'precision' => 3,
                'subunit' => 100,
                'symbol' => 'JD',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'KZT' => [
                'name' => 'Tenge',
                'abbr' => 'KZT',
                'code' => '398',
                'subunit_name' => 'Tïın',
                'locale' => 'kk_KZ',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₸',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'KES' => [
                'name' => 'Kenyan Shilling',
                'abbr' => 'KES',
                'code' => '404',
                'subunit_name' => 'Cent',
                'locale' => 'en_US',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'KSh',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'KPW' => [
                'name' => 'North Korean Won',
                'abbr' => 'KPW',
                'code' => '408',
                'subunit_name' => 'Chon',
                'locale' => 'ko_KP',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₩',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'KRW' => [
                'name' => 'Won',
                'abbr' => 'KRW',
                'code' => '410',
                'subunit_name' => 'Jeon',
                'locale' => 'ko_KR',
                'precision' => 0,
                'subunit' => 1,
                'symbol' => '₩',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'KWD' => [
                'name' => 'Kuwaiti Dinar',
                'abbr' => 'KWD',
                'code' => '414',
                'subunit_name' => 'Fils',
                'locale' => 'ar_KW',
                'precision' => 3,
                'subunit' => 1000,
                'symbol' => 'KD',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'KGS' => [
                'name' => 'Som',
                'abbr' => 'KGS',
                'code' => '417',
                'subunit_name' => 'Tyiyn',
                'locale' => 'ky_KG',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'лв',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'LAK' => [
                'name' => 'Lao Kip',
                'abbr' => 'LAK',
                'code' => '418',
                'subunit_name' => 'Att',
                'locale' => 'lo_LA',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₭',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'LBP' => [
                'name' => 'Lebanese Pound',
                'abbr' => 'LBP',
                'code' => '422',
                'subunit_name' => 'Piastre',
                'locale' => 'ar_LB',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '£',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'LSL' => [
                'name' => 'Loti',
                'abbr' => 'LSL',
                'code' => '426',
                'subunit_name' => 'Sente',
                'locale' => 'en_LS',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'M',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'ZAR' => [
                'name' => 'Rand',
                'abbr' => 'ZAR',
                'code' => '710',
                'subunit_name' => 'Cent',
                'locale' => 'en_ZA',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'R',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'LRD' => [
                'name' => 'Liberian Dollar',
                'abbr' => 'LRD',
                'code' => '430',
                'subunit_name' => 'Cent',
                'locale' => 'en_LR',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'LYD' => [
                'name' => 'Libyan Dinar',
                'abbr' => 'LYD',
                'code' => '434',
                'subunit_name' => 'Dirham',
                'locale' => 'ar_LY',
                'precision' => 3,
                'subunit' => 1000,
                'symbol' => 'LD',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'CHF' => [
                'name' => 'Swiss Franc',
                'abbr' => 'CHF',
                'code' => '756',
                'subunit_name' => 'Rappen',
                'locale' => 'de_CH',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'Fr.',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'MOP' => [
                'name' => 'Pataca',
                'abbr' => 'MOP',
                'code' => '446',
                'subunit_name' => 'Avos',
                'locale' => 'pt_MO',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'MOP$',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'MKD' => [
                'name' => 'Denar',
                'abbr' => 'MKD',
                'code' => '807',
                'subunit_name' => 'Deni',
                'locale' => 'mk_MK',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'ден',
                'symbol_first' => false,
                'decimal_mark' => ',',
                'thousands_separator' => '',
            ],

            'MGA' => [
                'name' => 'Malagasy Ariary',
                'abbr' => 'MGA',
                'code' => '969',
                'subunit_name' => 'Iraimbilanja',
                'locale' => 'mg_MG',
                'precision' => 2,
                'subunit' => 5,
                'symbol' => 'Ar',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'MWK' => [
                'name' => 'Malawi Kwacha',
                'abbr' => 'MWK',
                'code' => '454',
                'subunit_name' => 'Tambala',
                'locale' => 'ny_MW',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'MK',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'MYR' => [
                'name' => 'Malaysian Ringgit',
                'abbr' => 'MYR',
                'code' => '458',
                'subunit_name' => 'Sen',
                'locale' => 'ms_MY',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'RM',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'MVR' => [
                'name' => 'Rufiyaa',
                'abbr' => 'MVR',
                'code' => '462',
                'subunit_name' => 'Laari',
                'locale' => 'dv_MV',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'Rf',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'MRU' => [
                'name' => 'Ouguiya',
                'abbr' => 'MRU',
                'code' => '929',
                'subunit_name' => 'Khoums',
                'locale' => 'ar_MR',
                'precision' => 2,
                'subunit' => 5,
                'symbol' => 'UM',
                'symbol_first' => false,
                'decimal_mark' => ',',
                'thousands_separator' => '',
            ],

            'MUR' => [
                'name' => 'Mauritius Rupee',
                'abbr' => 'MUR',
                'code' => '480',
                'subunit_name' => 'Cent',
                'locale' => 'fr_MU',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₨',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'MXN' => [
                'name' => 'Mexican Peso',
                'abbr' => 'MXN',
                'code' => '484',
                'subunit_name' => 'Centavo',
                'locale' => 'es_MX',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'MDL' => [
                'name' => 'Moldovan Leu',
                'abbr' => 'MDL',
                'code' => '498',
                'subunit_name' => 'Ban',
                'locale' => 'en_FM',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'lei',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'MNT' => [
                'name' => 'Tugrik',
                'abbr' => 'MNT',
                'code' => '496',
                'subunit_name' => 'Möngö',
                'locale' => 'mn_MN',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₮',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'MAD' => [
                'name' => 'Moroccan Dirham',
                'abbr' => 'MAD',
                'code' => '504',
                'subunit_name' => 'Centime',
                'locale' => 'ar_MA',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'د.م.',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'MZN' => [
                'name' => 'Mozambique Metical',
                'abbr' => 'MZN',
                'code' => '943',
                'subunit_name' => 'Centavo',
                'locale' => 'pt_MZ',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'MT',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'MMK' => [
                'name' => 'Kyat',
                'abbr' => 'MMK',
                'code' => '104',
                'subunit_name' => 'Øre',
                'locale' => 'da_DK',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'K',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'NAD' => [
                'name' => 'Namibia Dollar',
                'abbr' => 'NAD',
                'code' => '516',
                'subunit_name' => 'Pya',
                'locale' => 'my_MN',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'NPR' => [
                'name' => 'Nepalese Rupee',
                'abbr' => 'NPR',
                'code' => '524',
                'subunit_name' => 'Paisa',
                'locale' => 'ne_NP',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₨',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'NIO' => [
                'name' => 'Cordoba Oro',
                'abbr' => 'NIO',
                'code' => '558',
                'subunit_name' => 'Centavo',
                'locale' => 'es_NI',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'C$',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'NGN' => [
                'name' => 'Naira',
                'abbr' => 'NGN',
                'code' => '566',
                'subunit_name' => 'kobo',
                'locale' => 'en_NG',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₦',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'OMR' => [
                'name' => 'Rial Omani',
                'abbr' => 'OMR',
                'code' => '512',
                'subunit_name' => 'Baisa',
                'locale' => 'ar_OM',
                'precision' => 3,
                'subunit' => 1000,
                'symbol' => '﷼',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'PKR' => [
                'name' => 'Pakistan Rupee',
                'abbr' => 'PKR',
                'code' => '586',
                'subunit_name' => 'Paisa',
                'locale' => 'ur_PK',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₨',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'PAB' => [
                'name' => 'Balboa',
                'abbr' => 'PAB',
                'code' => '590',
                'subunit_name' => 'Centésimo',
                'locale' => 'es_PA',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'B/.',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'PGK' => [
                'name' => 'Kina',
                'abbr' => 'PGK',
                'code' => '598',
                'subunit_name' => 'Toea',
                'locale' => 'en_PG',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'K',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'PYG' => [
                'name' => 'Guarani',
                'abbr' => 'PYG',
                'code' => '600',
                'subunit_name' => 'Céntimo',
                'locale' => 'es_PY',
                'precision' => 0,
                'subunit' => 1,
                'symbol' => 'Gs',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'PEN' => [
                'name' => 'Sol',
                'abbr' => 'PEN',
                'code' => '604',
                'subunit_name' => 'Céntimo',
                'locale' => 'es_PE',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'S/.',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'PHP' => [
                'name' => 'Philippine Peso',
                'abbr' => 'PHP',
                'code' => '608',
                'subunit_name' => 'Sentimo',
                'locale' => 'en_PH',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₱',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'PLN' => [
                'name' => 'Zloty',
                'abbr' => 'PLN',
                'code' => '985',
                'subunit_name' => 'Grosz',
                'locale' => 'pl_PL',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'zł',
                'symbol_first' => false,
                'decimal_mark' => ',',
                'thousands_separator' => ' ',
            ],

            'QAR' => [
                'name' => 'Qatari Riyal',
                'abbr' => 'QAR',
                'code' => '634',
                'subunit_name' => 'Dirham',
                'locale' => 'ar_QA',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '﷼',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'RON' => [
                'name' => 'Romanian Leu',
                'abbr' => 'RON',
                'code' => '946',
                'subunit_name' => 'Bani',
                'locale' => 'ro_RO',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'lei',
                'symbol_first' => true,
                'decimal_mark' => ',',
                'thousands_separator' => '.',
            ],

            'RUB' => [
                'name' => 'Russian Ruble',
                'abbr' => 'RUB',
                'code' => '643',
                'subunit_name' => 'Kopeck',
                'locale' => 'ru_RU',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₽',
                'symbol_first' => false,
                'decimal_mark' => ',',
                'thousands_separator' => '',
            ],

            'RWF' => [
                'name' => 'Rwanda Franc',
                'abbr' => 'RWF',
                'code' => '646',
                'subunit_name' => 'Centime',
                'locale' => 'rw_RW',
                'precision' => 0,
                'subunit' => 1,
                'symbol' => 'R₣',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'SHP' => [
                'name' => 'Saint Helena Pound',
                'abbr' => 'SHP',
                'code' => '654',
                'subunit_name' => 'Penny',
                'locale' => 'en_SH',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '£',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'WST' => [
                'name' => 'Tala',
                'abbr' => 'WST',
                'code' => '882',
                'subunit_name' => 'Sene',
                'locale' => 'sm_WS',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'WS$',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'STN' => [
                'name' => 'Dobra',
                'abbr' => 'STN',
                'code' => '930',
                'subunit_name' => 'Centimo',
                'locale' => 'pt_ST',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'Db',
                'symbol_first' => false,
                'decimal_mark' => ',',
                'thousands_separator' => '',
            ],

            'SAR' => [
                'name' => 'Saudi Riyal',
                'abbr' => 'SAR',
                'code' => '682',
                'subunit_name' => 'Hallallah',
                'locale' => 'ar_SA',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '﷼',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'RSD' => [
                'name' => 'Serbian Dinar',
                'abbr' => 'RSD',
                'code' => '941',
                'subunit_name' => 'Para',
                'locale' => 'sr_SR',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'дин.',
                'symbol_first' => false,
                'decimal_mark' => ',',
                'thousands_separator' => '.',
            ],

            'SCR' => [
                'name' => 'Seychelles Rupee',
                'abbr' => 'SCR',
                'code' => '690',
                'subunit_name' => 'Cent',
                'locale' => 'fr_SC',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₨',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'SLL' => [
                'name' => 'Leone',
                'abbr' => 'SLL',
                'code' => '694',
                'subunit_name' => 'Cent',
                'locale' => 'en_SL',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'Le',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'SLE' => [
                'name' => 'Leone',
                'abbr' => 'SLE',
                'code' => '925',
                'subunit_name' => 'Cent',
                'locale' => 'en_SL',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'Le',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'SGD' => [
                'name' => 'Singapore Dollar',
                'abbr' => 'SGD',
                'code' => '702',
                'subunit_name' => 'Cent',
                'locale' => 'en_SG',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'S$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'SBD' => [
                'name' => 'Solomon Islands Dollar',
                'abbr' => 'SBD',
                'code' => '090',
                'subunit_name' => 'Cent',
                'locale' => 'en_SB',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'SOS' => [
                'name' => 'Somali Shilling',
                'abbr' => 'SOS',
                'code' => '706',
                'subunit_name' => 'Cent',
                'locale' => 'so_SO',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'S',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'SSP' => [
                'name' => 'South Sudanese Pound',
                'abbr' => 'SSP',
                'code' => '728',
                'subunit_name' => 'Piaster',
                'locale' => 'ar_SS',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '£',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'LKR' => [
                'name' => 'Sri Lanka Rupee',
                'abbr' => 'LKR',
                'code' => '144',
                'subunit_name' => 'Øre',
                'locale' => 'da_DK',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₨',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'SDG' => [
                'name' => 'Sudanese Pound',
                'abbr' => 'SDG',
                'code' => '938',
                'subunit_name' => 'Piastre',
                'locale' => 'ar_SD',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'ج.س.',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'SRD' => [
                'name' => 'Surinam Dollar',
                'abbr' => 'SRD',
                'code' => '968',
                'subunit_name' => 'Cent',
                'locale' => 'nl_SR',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'SEK' => [
                'name' => 'Swedish Krona',
                'abbr' => 'SEK',
                'code' => '752',
                'subunit_name' => 'Øre',
                'locale' => 'sv_SE',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'kr',
                'symbol_first' => false,
                'decimal_mark' => ',',
                'thousands_separator' => '',
            ],

            'SYP' => [
                'name' => 'Syrian Pound',
                'abbr' => 'SYP',
                'code' => '760',
                'subunit_name' => 'Piastre',
                'locale' => 'ar_SY',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '£S',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'TWD' => [
                'name' => 'New Taiwan Dollar',
                'abbr' => 'TWD',
                'code' => '901',
                'subunit_name' => 'Cent',
                'locale' => 'zh_TW',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'NT$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'TJS' => [
                'name' => 'Somoni',
                'abbr' => 'TJS',
                'code' => '972',
                'subunit_name' => 'Diram',
                'locale' => 'tg_TJ',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'SM',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'TZS' => [
                'name' => 'Tanzanian Shilling',
                'abbr' => 'TZS',
                'code' => '834',
                'subunit_name' => 'Cent',
                'locale' => 'sw_TZ',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'TSh',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'THB' => [
                'name' => 'Baht',
                'abbr' => 'THB',
                'code' => '764',
                'subunit_name' => 'Satang',
                'locale' => 'th_TH',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '฿',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'TOP' => [
                'name' => 'Pa’anga',
                'abbr' => 'TOP',
                'code' => '776',
                'subunit_name' => 'Seniti',
                'locale' => 'to_TO',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'T$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'TTD' => [
                'name' => 'Trinidad and Tobago Dollar',
                'abbr' => 'TTD',
                'code' => '780',
                'subunit_name' => 'Cent',
                'locale' => 'en_TT',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'TT$',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'TND' => [
                'name' => 'Tunisian Dinar',
                'abbr' => 'TND',
                'code' => '788',
                'subunit_name' => 'Millime',
                'locale' => 'ar_TN',
                'precision' => 3,
                'subunit' => 1000,
                'symbol' => 'د.ت',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'TRY' => [
                'name' => 'Turkish Lira',
                'abbr' => 'TRY',
                'code' => '949',
                'subunit_name' => 'Kuruş',
                'locale' => 'ar_TN',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₺',
                'symbol_first' => true,
                'decimal_mark' => ',',
                'thousands_separator' => '.',
            ],

            'TMT' => [
                'name' => 'Turkmenistan New Manat',
                'abbr' => 'TMT',
                'code' => '934',
                'subunit_name' => 'Tenge',
                'locale' => 'tk_TM',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'T',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'UGX' => [
                'name' => 'Uganda Shilling',
                'abbr' => 'UGX',
                'code' => '800',
                'subunit_name' => 'Cent',
                'locale' => 'en_US',
                'precision' => 0,
                'subunit' => 1,
                'symbol' => 'USh',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'UAH' => [
                'name' => 'Hryvnia',
                'abbr' => 'UAH',
                'code' => '980',
                'subunit_name' => 'Kopiyka',
                'locale' => 'uk_UA',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '₴',
                'symbol_first' => false,
                'decimal_mark' => ',',
                'thousands_separator' => '',
            ],

            'AED' => [
                'name' => 'UAE Dirham',
                'abbr' => 'AED',
                'code' => '784',
                'subunit_name' => 'Fils',
                'locale' => 'ar_AE',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'د.إ',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'UYU' => [
                'name' => 'Peso Uruguayo',
                'abbr' => 'UYU',
                'code' => '858',
                'subunit_name' => 'Centésimo',
                'locale' => 'es_UY',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$U',
                'symbol_first' => true,
                'decimal_mark' => ',',
                'thousands_separator' => '.',
            ],

            'UZS' => [
                'name' => 'Uzbekistan Sum',
                'abbr' => 'UZS',
                'code' => '860',
                'subunit_name' => 'Tiyin',
                'locale' => 'uz_UZ',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'лв',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'VUV' => [
                'name' => 'Vatu',
                'abbr' => 'VUV',
                'code' => '548',
                'subunit_name' => '',
                'locale' => 'bi_VU',
                'precision' => 0,
                'subunit' => 1,
                'symbol' => 'VT',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'VES' => [
                'name' => 'Bolívar Soberano',
                'abbr' => 'VES',
                'code' => '928',
                'subunit_name' => 'Céntimo',
                'locale' => 'es_VE',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'Bs.S',
                'symbol_first' => true,
                'decimal_mark' => ',',
                'thousands_separator' => '',
            ],

            'VED' => [
                'name' => 'Bolívar Soberano',
                'abbr' => 'VED',
                'code' => '926',
                'subunit_name' => 'Céntimo',
                'locale' => 'es_VE',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'Bs.',
                'symbol_first' => true,
                'decimal_mark' => ',',
                'thousands_separator' => '',
            ],

            'VND' => [
                'name' => 'Dong',
                'abbr' => 'VND',
                'code' => '704',
                'subunit_name' => 'Hào',
                'locale' => 'vi_VN',
                'precision' => 0,
                'subunit' => 1,
                'symbol' => '₫',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'YER' => [
                'name' => 'Yemeni Rial',
                'abbr' => 'YER',
                'code' => '886',
                'subunit_name' => 'Fils',
                'locale' => 'ar_YE',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '﷼',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'ZMW' => [
                'name' => 'Zambian Kwacha',
                'abbr' => 'ZMW',
                'code' => '967',
                'subunit_name' => 'Ngwee',
                'locale' => 'en_ZM',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => 'ZK',
                'symbol_first' => false,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],

            'ZWL' => [
                'name' => 'Zimbabwe Dollar',
                'abbr' => 'ZWL',
                'code' => '932',
                'subunit_name' => 'Cent',
                'locale' => 'en_ZW',
                'precision' => 2,
                'subunit' => 100,
                'symbol' => '$',
                'symbol_first' => true,
                'decimal_mark' => '.',
                'thousands_separator' => ',',
            ],
        ];

        foreach ($currencies as $currency) {
            Currency::create($currency);
        }
    }
}
